from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Lineage columns the connector adds to every row from the authenticated export context.
# They are repeated per table so each table documents its own join keys.
_CONTEXT_COLUMNS = {
    "bucketeer_contract_version": "Version of the Bucketeer analytics export contract this row was read under.",
    "bucketeer_organization_id": "Id of the Bucketeer organization the API key belongs to.",
    "bucketeer_project_id": "Id of the Bucketeer project the environment belongs to.",
    "bucketeer_project_url_code": "URL code of the Bucketeer project, as it appears in Bucketeer URLs.",
    "bucketeer_environment_id": "Id of the environment the API key is bound to. Set from the authenticated export context, never from the record, and forms half of the primary key.",
    "bucketeer_environment_name": "Display name of the environment the API key is bound to.",
    "bucketeer_environment_url_code": "URL code of the environment, as it appears in Bucketeer URLs.",
}

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "feature_flags": {
        "description": "A Bucketeer feature flag with its variations, targeting rules, prerequisites, and rollout state. Describes the flag's configuration as of the sync, not any individual evaluation.",
        "docs_url": "https://docs.bucketeer.io/api-reference/feature-flags",
        "columns": {
            "id": "Id of the feature flag, unique within the environment.",
            "name": "Display name of the feature flag.",
            "description": "Description of what the flag controls.",
            "enabled": "Whether the flag is currently serving its targeting rules rather than its off variation.",
            "archived": "Whether the flag is archived. Archived flags are still returned.",
            "deleted": "Whether the flag is soft-deleted in Bucketeer.",
            "version": "Version number of the flag, incremented on each configuration change. Join to bucketeer_feature_version on evaluation events to know which configuration a user saw.",
            "variations": "The variations the flag can serve, each with its own id, value, name, and description. Join variation id to bucketeer_variation_id on evaluation events.",
            "targets": "Per-variation lists of individually targeted user ids.",
            "rules": "Ordered targeting rules. The id of the matched rule appears as bucketeer_rule_id on evaluation events.",
            "prerequisites": "Other flags that must evaluate to a given variation before this flag's rules apply.",
            "offVariation": "Id of the variation served while the flag is disabled.",
            "tags": "Tags applied to the flag.",
            "maintainer": "Email of the account responsible for the flag.",
            "ttl": "Time to live, in seconds, for the flag's cached evaluation.",
            "samplingSeed": "Seed used to keep percentage rollouts stable across evaluations.",
            "createdAt": "When the flag was created, in Unix seconds.",
            "updatedAt": "When the flag was last changed, in Unix seconds. Bucketeer exposes no server-side filter on this, so it cannot drive an incremental sync.",
            **_CONTEXT_COLUMNS,
        },
    },
    "segments": {
        "description": "A reusable set of targeting rules that flags reference by id. Member lists are deliberately not exported.",
        "docs_url": "https://docs.bucketeer.io/api-reference/segments",
        "columns": {
            "id": "Id of the segment, unique within the environment.",
            "name": "Display name of the segment.",
            "description": "Description of who the segment covers.",
            "rules": "Rules defining membership of the segment.",
            "status": "Whether the segment's user list has finished uploading.",
            "includedUserCount": "Number of users explicitly included in the segment. A count only; the member list itself is not exported.",
            "isInUseStatus": "Whether any feature flag currently references the segment.",
            "features": "Feature flags that reference this segment.",
            "deleted": "Whether the segment is soft-deleted in Bucketeer.",
            "createdAt": "When the segment was created, in Unix seconds.",
            "updatedAt": "When the segment was last changed, in Unix seconds.",
            **_CONTEXT_COLUMNS,
        },
    },
    "experiments": {
        "description": "A Bucketeer experiment binding a feature flag version to a set of goals over a scheduled window.",
        "docs_url": "https://docs.bucketeer.io/api-reference/experiments",
        "columns": {
            "id": "Id of the experiment, unique within the environment.",
            "name": "Display name of the experiment.",
            "description": "Description of what the experiment tests.",
            "featureId": "Id of the feature flag under test. Join to feature_flags.id.",
            "featureVersion": "Version of the flag the experiment runs against. Join with featureId to pin the exact configuration.",
            "variations": "The flag variations participating in the experiment.",
            "baseVariationId": "Id of the variation treated as the control.",
            "goalIds": "Ids of the goals this experiment measures. Join to goals.id and to bucketeer_goal_id on goal events.",
            "status": "Lifecycle state of the experiment: waiting, running, stopped, or force stopped.",
            "startAt": "When the experiment window opens, in Unix seconds.",
            "stopAt": "When the experiment window closes, in Unix seconds.",
            "stoppedAt": "When the experiment was actually stopped, in Unix seconds.",
            "maintainer": "Email of the account responsible for the experiment.",
            "archived": "Whether the experiment is archived.",
            "deleted": "Whether the experiment is soft-deleted in Bucketeer.",
            "createdAt": "When the experiment was created, in Unix seconds.",
            "updatedAt": "When the experiment was last changed, in Unix seconds.",
            **_CONTEXT_COLUMNS,
        },
    },
    "goals": {
        "description": "A conversion goal that experiments measure. Join to goal events by id.",
        "docs_url": "https://docs.bucketeer.io/api-reference/goals",
        "columns": {
            "id": "Id of the goal, unique within the environment. Matches bucketeer_goal_id on goal events.",
            "name": "Display name of the goal.",
            "description": "Description of what the goal measures.",
            "isInUseStatus": "Whether any experiment currently references the goal.",
            "archived": "Whether the goal is archived. Archived goals are still returned.",
            "deleted": "Whether the goal is soft-deleted in Bucketeer.",
            "createdAt": "When the goal was created, in Unix seconds.",
            "updatedAt": "When the goal was last changed, in Unix seconds.",
            **_CONTEXT_COLUMNS,
        },
    },
    "audit_logs": {
        "description": "A record of a configuration change in Bucketeer: who changed which entity, when, and what the entity looked like before and after.",
        "docs_url": "https://docs.bucketeer.io/api-reference/audit-logs",
        "columns": {
            "id": "Id of the audit log entry.",
            "timestamp": "When the change happened, in Unix seconds. This is the only export field Bucketeer can filter on server-side.",
            "entityType": "Type of entity that changed, such as feature flag, goal, or experiment.",
            "entityId": "Id of the entity that changed. Join to the id column of the matching table.",
            "type": "The kind of change, such as created, updated, archived, or deleted.",
            "editor": "Who made the change, as an email and role.",
            "entityData": "JSON string of the entity after the change.",
            "previousEntityData": "JSON string of the entity before the change.",
            "localizedMessage": "Human-readable description of the change.",
            "options": "Comment and related metadata recorded with the change.",
            **_CONTEXT_COLUMNS,
        },
    },
    "code_references": {
        "description": "A place in a source repository where a feature flag is referenced. Useful for finding flags that are live in Bucketeer but no longer used in code.",
        "docs_url": "https://docs.bucketeer.io/api-reference/code-references",
        "columns": {
            "id": "Id of the code reference.",
            "featureId": "Id of the referenced feature flag. Join to feature_flags.id.",
            "filePath": "Path of the file containing the reference.",
            "lineNumber": "Line number of the reference within the file.",
            "codeSnippet": "The surrounding lines of source code.",
            "contentHash": "Hash of the snippet, used to detect a moved or changed reference.",
            "aliases": "Other identifiers in code that resolve to the same flag.",
            "repositoryName": "Name of the repository.",
            "repositoryOwner": "Owner or organization of the repository.",
            "repositoryType": "Hosting provider of the repository, such as GitHub or GitLab.",
            "repositoryBranch": "Branch the reference was found on.",
            "commitHash": "Commit the reference was found in.",
            "environmentId": "Environment id as recorded on the record itself. Prefer bucketeer_environment_id, which comes from the authenticated export context.",
            "sourceUrl": "Link to the referenced line in the repository.",
            "branchUrl": "Link to the branch in the repository.",
            "fileExtension": "Extension of the file, such as go, ts, or cpp.",
            "createdAt": "When the reference was first recorded, in Unix seconds.",
            "updatedAt": "When the reference was last updated, in Unix seconds.",
            **_CONTEXT_COLUMNS,
        },
    },
}
